/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dreamaker_chromium_AWTUtil */

#ifndef _Included_com_dreamaker_chromium_AWTUtil
#define _Included_com_dreamaker_chromium_AWTUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dreamaker_chromium_AWTUtil
 * Method:    getWindowHandleInWindows
 * Signature: (Ljavax/swing/JFrame;)I
 */
JNIEXPORT jint JNICALL Java_com_dreamaker_chromium_AWTUtil_getWindowHandleInWindows
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
